const GET_MOVIES_LIST = 'MOVIESLIST/GET_MOVIES_LIST';
const GET_MOVIES_LIST_SUCCESS = 'MOVIESLIST/GET_MOVIES_LIST_SUCCESS';
const GET_MOVIES_LIST_FAIL = 'MOVIESLIST/GET_MOVIES_LIST_FAIL';



export { GET_MOVIES_LIST, GET_MOVIES_LIST_SUCCESS, GET_MOVIES_LIST_FAIL }
