const GET_MOVIE_DETAIL = 'MOVIEDETAIL/GET_MOVIE_DETAIL';
const GET_MOVIE_DETAIL_SUCCESS = 'MOVIEDETAIL/GET_MOVIE_DETAIL_SUCCESS';
const GET_MOVIE_DETAIL_FAIL = 'MOVIEDETAIL/GET_MOVIE_DETAIL_FAIL';

export { GET_MOVIE_DETAIL, GET_MOVIE_DETAIL_SUCCESS, GET_MOVIE_DETAIL_FAIL }
